apiVersion: v1
kind: Service
metadata:
  name: geofence
spec:
  type: ClusterIP
  selector:
    app: geofence
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: grpc
      port: 50051
      targetPort: grpc
